[project]
name = "chem-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "accelerate>=1.14.0",
    "aiida-pseudo>=1.8.0",
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "jupyter-client>=8.9.1",
    "jupyter-server>=2.20.0",
    "jupyterlab>=4.6.2",
    "mp-api>=0.46.4",
    "nbconvert>=7.17.1",
    "notebook>=7.6.1",
    "numpy>=2.5.0",
    "pathlib>=1.0.1",
    "pseudohub>=0.1.1",
    "pymatgen>=2026.5.4",
    "pyzmq>=27.1.0",
    "torch>=2.12.1",
    "tqdm>=4.68.3",
    "transformers>=5.12.1",
]
